language: python
python:
  - "3.5"

before_script:
  - pip install -r requirements.txt

script:
  - travis-sphinx -s source build
  - echo "ds.futureistech.com" > target/doc/build/CNAME

after_success:
- travis-sphinx deploy
